[package]
name = "byside"
version = "1.3.1"
description = "Compare two images side by side"
authors = ["Cao Le"]
edition = "2021"

[lib]
name = "byside_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-dialog = "2"
image = { version = "0.25", default-features = false, features = [
  "bmp", "gif", "ico", "jpeg", "png", "tiff", "webp"
] }

[target.'cfg(target_os = "macos")'.dependencies]
tauri = { version = "2", features = ["macos-private-api"] }

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
